### ISSUE TITLE
IP Loopback on Mac disabled

### ISSUE THREAD

**Issue by ileslie71** [chrisschmitz/commandbox-hostupdater#6]
This is a great module but unfortunately it doesn't seem to work on Mac - well for me at least.
As far as I can tell the loop back addresses for local host are all blocked by Mac OS apart from 127.0.0.1.
So while the module seems to work perfectly - the hosts file is updated correctly it cannot get a site at the IP allocated.
It is entirely possible I'm missing something obvious of course but as far as I can find out Apple has for whatever reason disabled all loopback addresses apart from 127.0.0.1.
Not your fault of course but if I'm not wring here it probably needs a note in system requirements to this effect.

**Comment by chrisschmitz** [comment]
Hi,
I just comitted v 1.2.2-alpha which includes a command for MacOS that makes it accept other IP addresses besides 127.0.0.1 as local.

For now the drawback is that you have to start CommandBox with sudo.
To install that version please do isntall commandbox-hostupdater@1.2.2-alpha

I will rewrite the code so that you don't need to start CommandBox with sudo, but that may take some time as I don't have a Mac at hand every day ;-)

**Comment by chrisschmitz** [comment]
apparently the publishing of 1.2.2-alpha didn't work as expected... Brad Wood will look into that.
I simply pushed the change to the Github repo.
Pls. remember that for the time being you need to start CommandBox with 'sudo box'

I know that this will cause CommandBox to create a new home directory... you can get around that by creating a commandbox.properties in the same directory where the executable is. In commandbox.properties set the home path like so:
commandbox_home=/path/to/your/old/commandbox-dir
(see https://commandbox.ortusbooks.com/content/setup/installation.html)

**Comment by ileslie71** [comment]
Thanks Chris. That's great. I will give this a try tonight and let you know how I get on.
